### ISSUE TITLE
Address/Details Order

### ISSUE THREAD

**Issue by ekamptner** [CityOfNewYork/poletop-finder#11]
On-Street
Between Street 1 and Street 2
Borough, NY Zipcode
Community District
Community Board

Details Section:
Reservation ID
Ownership (aka Pole Class)
Franchisee Name
Franchise Contract Zone (aka Zone)
Reservation Date
Additional Notes (Advisories section)

**Comment by cmenedes** [comment]
Addressed in c9e186a with Reservation ID as unique identifier
