### ISSUE TITLE
add padding in css for filters panel symbols

### ISSUE THREAD

**Issue by ekamptner** [CityOfNewYork/poletop-finder#14]
When highlighting the checkbox there is a slight overlap in symbol/checkbox bounding box. Verify against other translations as well. 
![image](https://user-images.githubusercontent.com/7623478/89587120-efa60c80-d80e-11ea-9e11-9eebc057a264.png)

![image](https://user-images.githubusercontent.com/7623478/89664154-b5874a00-d8a4-11ea-95db-6d5260a791aa.png)

**Comment by timkeane** [comment]
fixed in 
8c86f6d
