### ISSUE TITLE
Verify community board sum is correct

### ISSUE THREAD

**Issue by ekamptner** [CityOfNewYork/poletop-finder#19]
Spot checking, some seem incorrect when compared to Open Data. 

Ex. OpenData returns
CB 105 - 392 sites
CB 503- 358 sites

I'm referencing the visualization feature in OpenData to get a quick read on these numbers -- https://data.cityofnewyork.us/d/tbgj-tdd6/visualization

**Comment by timkeane** [comment]
fixed in e881322
