### ISSUE TITLE
Compressed view (mobile/small view Desktop) doesn't show nearest facility

### ISSUE THREAD

**Issue by ekamptner** [CityOfNewYork/poletop-finder#26]
On Desktop (small view)-- Does not list nearest facility
![image](https://user-images.githubusercontent.com/7623478/89645254-64b52880-d887-11ea-8782-3832a9d073e6.png)

On Mobile (iPhone 7) -- the nearest facility is displayed but does not align with list of locations in details panel (will attach photo if needed)

**Comment by timkeane** [comment]
fixed in ad9853c
