### ISSUE TITLE
Display all CB clusters on land masses

### ISSUE THREAD

**Issue by ekamptner** [CityOfNewYork/poletop-finder#27]
Is this possible? Some CB (centroids?) are over water and may be confusing -- 

![image](https://user-images.githubusercontent.com/7623478/89647332-6aad0880-d88b-11ea-94c4-030c95132b48.png)

**Comment by ekamptner** [comment]
I'll update the CB csv with coords and send back to @timkeane for implementation

**Comment by timkeane** [comment]
@ekamptner  just commit the csv change it will magicall work :-)

**Comment by ekamptner** [comment]
Resolved in latest edits to community_board.csv
