### ISSUE TITLE
Zone - "Franchise Contract Zone"

### ISSUE THREAD

**Issue by ekamptner** [CityOfNewYork/poletop-finder#3]
Include more descriptive text for Zone 

Add attribute label as "Franchise Contract Zone" instead of "Zone"

A = A: Manhattan South of 96th Street
B = B: All boroughs excluding those areas in Zones A and C
C = C: Parts of Harlem, the South Bronx and East New York (Brooklyn)

**Comment by cmenedes** [comment]
Addressed in commit 1112779
