### ISSUE TITLE
Advisories - "Additional Notes"

### ISSUE THREAD

**Issue by ekamptner** [CityOfNewYork/poletop-finder#4]
Set Advisory section header to "Additional Notes". 

Display following text for each advisory type:

Pole is located within **[park_advisory]** under the jurisdiction of the Department of Parks and Recreation.
Pole is located near or within the **[historic_advisory]** under the jurisdiction of the Landmarks Preservation Commission. 
Pole is located adjacent to **[scenic_advisory]** scenic landmark under the jurisdiction of the Landmarks Preservation Commission. 
Pole is located within Business Improvement District **[bid_advisory]**.
Pole is located within 20 feet of **[school_advisory]**.

**Comment by cmenedes** [comment]
Addressed in c9e186a
