### ISSUE TITLE
make details background color same color as feature

### ISSUE THREAD

**Issue by ekamptner** [CityOfNewYork/poletop-finder#41]
When user clicks the details for a "light grey" background feature, the details are yellow. When viewing them, it can be a little confusing. The background color of details section should alternate the same as the main feature details section. 

I see this may be a nyc-lib feature. 

Clicking feature with "light grey" background displays yellow details-- 
![image](https://user-images.githubusercontent.com/7623478/89958426-d1258400-dc07-11ea-91cd-0de2df2a21f5.png)

**Comment by timkeane** [comment]
fixed in eea0a12
