### ISSUE TITLE
keyboard appears on click (seen on Galaxy 9+)

### ISSUE THREAD

**Issue by ekamptner** [CityOfNewYork/poletop-finder#44]
Reported by QA -- on Android device, keyboard appears when clicking feature. I don't see this behavior on iPhones.

![image](https://user-images.githubusercontent.com/7623478/90277009-d1ee2e00-de32-11ea-9d87-a0bd2ab91bc1.png)

**Comment by cmenedes** [comment]
I see this on my Galaxy S10+ (Chrome and Samsung Internet). 
Once you close out one of the popups, it doesn't show up anymore when you click on a feature (at the community board level).
It also appears when you press "View Map" on the splash page.

**Comment by cmenedes** [comment]
Addressed in 4da9503
