### ISSUE TITLE
New "status" field in OpenData dataset

### ISSUE THREAD

**Issue by ekamptner** [CityOfNewYork/poletop-finder#45]
Dataset was recently updated to include a "status" field, replacing the previous field used for filters/symbology. 

1. Update symbology based on status field. Set "Proposed" to solid circle, "Approved" to solid circle with white check mark, "Installed" to wifi icon in solid circle
2. Update details to point to new status field 
3. Update filters based on status

**Comment by cmenedes** [comment]
Changes addressed in 28f3dc5

**Comment by ekamptner** [comment]
Confirmed. closing
