### ISSUE TITLE
Splash Text

### ISSUE THREAD

**Issue by ekamptner** [CityOfNewYork/poletop-finder#6]
**Use same first paragraph for web manifest**

This map includes locations of street light poles, traffic light poles, and utility poles that are approved for installation of mobile telecommunications equipment by companies authorized by the New York City Department of Information Technology and Telecommunications (DoITT). Today, these poletop locations are used to provide 4G across NYC and in the future may include additional pole-mounted equipment to support 5G. 

For more information on DoITT's Franchise agreements and poletop reservation process with mobile telecommunication companies, please visit [DoITT's website](https://www1.nyc.gov/site/doitt/business/franchise-process.page). 

Data published in this map is updated regularly and is available for download on [NYC OpenData ](https://data.cityofnewyork.us/City-Government/Mobile-Telecommunication-Franchise-Poletop-Install/tbgj-tdd6).

Buttons:
- View Map
- Screen Reader Instructions

**Comment by cmenedes** [comment]
Addressed in commit 1112779

**Comment by ekamptner** [comment]
Feedback -- 

Replace the "DoITT's website" link with this link --  https://www1.nyc.gov/site/doitt/business/mobile-telecom-franchises.page

**Comment by cmenedes** [comment]
Feedback addressed in f41d1d4
